services:

  mysql:
    image: mysql:latest
    container_name: pantryPlusDb
    profiles: [mysql]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@55w0rd
      MYSQL_DATABASE: PANTRY_PLUS
