services:

  postgres:
    image: postgres
    profiles: [postgres]
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  postgres-admin:
    image: adminer
    profiles: [postgres]
    restart: always
    ports:
      - 8080:8080

  mysql:
    image: mysql
    profiles: [mysql]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
